#!/usr/bin/env sh

set -eu

: ${GO:=go}

export GOOS=linux
export GOARCH=amd64

GITSHA=$(openssl sha1 -r main.go | cut -f1 -d ' ')
VERSION="git-${GITSHA:0:8}"
BUILDTIME="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

ldflags=
ldflags="${ldflags} -X main.commit=${GITSHA}"
ldflags="${ldflags} -X main.version=${VERSION}"
ldflags="${ldflags} -X main.buildTime=${BUILDTIME}"

# build binary
$GO build \
    -ldflags "${ldflags}" \
    -trimpath \
    -o BUILD/be_server_${GOOS}_${GOARCH} ./

# update deploy manifest
sed "s/version = \"latest\"/version = \"${VERSION}\"/" be_server.nomad > BUILD/be_server.nomad

echo "${VERSION} BUILD/be_server_${GOOS}_${GOARCH}"
