---
- name: install haproxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: install config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - haproxy restart
